#!/bin/bash

# RedMess Manual Setup Script
# For users who prefer step-by-step manual installation
# BRUTAL V3.0

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

echo -e "${RED}${BOLD}"
cat << "EOF"
╦═╗┌─┐┌┬┐╔╦╗┌─┐┌─┐┌─┐  ╔═╗┌─┐┌┬┐┬ ┬┌─┐
╠╦╝├┤  ││║║║├┤ └─┐└─┐  ╚═╗├┤  │ │ │├─┘
╩╚═└─┘─┴┘╩ ╩└─┘└─┘└─┘  ╚═╝└─┘ ┴ └─┘┴  
EOF
echo -e "${NC}${CYAN}Manual Installation - BRUTAL V3.0${NC}\n"

INSTALL_DIR="$HOME/.redmess"

echo -e "${YELLOW}This script will:${NC}"
echo -e "  1. Create directory structure"
echo -e "  2. Copy skills and tools"
echo -e "  3. Generate configuration file"
echo -e "  4. Set up database"
echo -e "  5. Create launcher scripts"
echo -e ""
echo -e "${CYAN}Installation directory: ${BLUE}$INSTALL_DIR${NC}\n"

read -p "Press Enter to continue or Ctrl+C to cancel..."

# Step 1: Create directories
echo -e "\n${BLUE}[1/7]${NC} Creating directory structure..."
mkdir -p "$INSTALL_DIR"/{config,skills,logs,workspace,backups}
mkdir -p "$INSTALL_DIR/skills/security"
mkdir -p "$INSTALL_DIR/telegram_bot"
echo -e "${GREEN}✓${NC} Directories created"

# Step 2: Copy skills
echo -e "\n${BLUE}[2/7]${NC} Installing security skills..."
if [ -d "security" ]; then
    cp -r security/* "$INSTALL_DIR/skills/security/" 2>/dev/null || true
    SKILL_COUNT=$(find "$INSTALL_DIR/skills/security" -name "*.md" 2>/dev/null | wc -l)
    echo -e "${GREEN}✓${NC} Installed $SKILL_COUNT skills"
else
    echo -e "${YELLOW}⚠${NC} Security skills not found in current directory"
fi

# Step 3: Copy Python modules
echo -e "\n${BLUE}[3/7]${NC} Installing Python modules..."
if [ -f "security/godmode_integration.py" ]; then
    cp security/godmode_integration.py "$INSTALL_DIR/telegram_bot/"
    echo -e "${GREEN}✓${NC} GODMODE integration copied"
fi

if [ -f "telegram_bot/bot.py" ]; then
    cp telegram_bot/bot.py "$INSTALL_DIR/telegram_bot/"
    echo -e "${GREEN}✓${NC} Telegram bot copied"
fi

# Step 4: Generate configuration
echo -e "\n${BLUE}[4/7]${NC} Generating configuration file..."
cat > "$INSTALL_DIR/config/redmess.yaml" << 'EOFCONFIG'
# RedMess Configuration
# Generated by manual setup script

system:
  version: "3.0.0"
  mode: "BRUTAL"
  install_dir: "~/.redmess"
  log_level: "INFO"

ai:
  provider: "openai"
  base_url: "https://api.openai.com/v1"
  api_key: "YOUR_API_KEY_HERE"
  model: "gpt-4"
  temperature: 0.9
  max_tokens: 4096
  stream: true
  timeout: 120

godmode:
  enabled: true
  primary_owner: 7570665912
  injection_detection: false
  content_boundaries: false
  refusal_override: true
  personality: "brutal"
  codewords:
    enabled: true
    boomba: true
    anarchist: true
    chemist: true
    hacker: true
  opsec_warnings: true

telegram:
  enabled: false
  bot_token: ""
  owner_id: 7570665912
  bot_username: "redmess_bot"
  typing_delay: 1.0
  max_message_length: 4096
  parse_mode: "Markdown"
  rate_limit:
    enabled: true
    max_requests_per_minute: 30
    max_requests_per_hour: 500
  allowed_users: []

offensive_security:
  skills_enabled: true
  categories:
    - apk_modding
    - reverse_engineering
    - web_exploitation
    - binary_exploitation
    - social_engineering
    - malware_development
    - network_hacking
    - mobile_hacking
    - cloud_security
    - cryptography
  tools_integration: true
  opsec_warnings: true
  auto_generation: true

workspace:
  base_dir: "~/.redmess/workspace"
  per_user_workspace: true
  auto_cleanup:
    enabled: true
    max_age_days: 30
    max_size_mb: 1000
  file_upload:
    enabled: true
    max_size_mb: 50
    service: "gofile"
    auto_upload_threshold_mb: 10

database:
  path: "~/.redmess/umiagent.db"
  type: "sqlite"
  backup:
    enabled: true
    interval_hours: 24
    keep_backups: 7

logging:
  log_dir: "~/.redmess/logs"
  levels:
    bot: "INFO"
    godmode: "DEBUG"
    skills: "INFO"
    api: "WARNING"
  rotation:
    enabled: true
    max_size_mb: 100
    keep_files: 10
  log_sensitive: false

advanced:
  concurrent_requests: 10
  request_timeout: 300
  max_context_messages: 100
  clear_context_after_hours: 24
  debug_mode: false
EOFCONFIG

echo -e "${GREEN}✓${NC} Configuration file created"
echo -e "${YELLOW}⚠${NC} Edit $INSTALL_DIR/config/redmess.yaml to add your API keys"

# Step 5: Create database
echo -e "\n${BLUE}[5/7]${NC} Creating database..."
python3 << 'EOFPYTHON'
import sqlite3
import os

db_path = os.path.expanduser("~/.redmess/umiagent.db")

conn = sqlite3.connect(db_path)
cursor = conn.cursor()

# GODMODE authorization table
cursor.execute('''
CREATE TABLE IF NOT EXISTS godmode_auth (
    user_id INTEGER PRIMARY KEY,
    tier TEXT NOT NULL,
    authorized_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP,
    notes TEXT
)
''')

# Rental system table
cursor.execute('''
CREATE TABLE IF NOT EXISTS rentals (
    user_id INTEGER PRIMARY KEY,
    tier TEXT NOT NULL,
    started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NOT NULL,
    payment_amount INTEGER,
    payment_method TEXT,
    is_active BOOLEAN DEFAULT 1
)
''')

# Usage logs
cursor.execute('''
CREATE TABLE IF NOT EXISTS usage_logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    command TEXT,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    success BOOLEAN DEFAULT 1
)
''')

# Insert primary owner
cursor.execute('''
INSERT OR IGNORE INTO godmode_auth (user_id, tier, notes)
VALUES (7570665912, 'PRIMARY_OWNER', 'Default owner - change in config')
''')

conn.commit()
conn.close()
print("Database created successfully")
EOFPYTHON

echo -e "${GREEN}✓${NC} Database created at $INSTALL_DIR/umiagent.db"

# Step 6: Create launcher scripts
echo -e "\n${BLUE}[6/7]${NC} Creating launcher scripts..."

# Hermes launcher
cat > "$INSTALL_DIR/start_hermes.sh" << 'EOFSCRIPT'
#!/bin/bash
cd "$(dirname "$0")"
export REDMESS_CONFIG="$PWD/config/redmess.yaml"
echo "🔥 Starting Hermes Agent - BRUTAL V3.0"
hermes chat
EOFSCRIPT
chmod +x "$INSTALL_DIR/start_hermes.sh"

# Bot launcher
cat > "$INSTALL_DIR/start_bot.sh" << 'EOFSCRIPT'
#!/bin/bash
cd "$(dirname "$0")"
export REDMESS_CONFIG="$PWD/config/redmess.yaml"
echo "🔥 Starting RedMess Telegram Bot - BRUTAL V3.0"
python3 telegram_bot/bot.py
EOFSCRIPT
chmod +x "$INSTALL_DIR/start_bot.sh"

# GODMODE injector launcher
cat > "$INSTALL_DIR/inject_godmode.sh" << 'EOFSCRIPT'
#!/bin/bash
cd "$(dirname "$0")"
echo "🔥 Injecting GODMODE into Hermes profile..."
python3 skills/security/godmode_injector.py
echo "✓ GODMODE injection complete"
EOFSCRIPT
chmod +x "$INSTALL_DIR/inject_godmode.sh"

echo -e "${GREEN}✓${NC} Launcher scripts created"

# Step 7: Install Python dependencies
echo -e "\n${BLUE}[7/7]${NC} Installing Python dependencies..."
if [ -f "requirements.txt" ]; then
    python3 -m pip install -r requirements.txt --user --quiet
    echo -e "${GREEN}✓${NC} Dependencies installed"
else
    echo -e "${YELLOW}⚠${NC} requirements.txt not found, skipping pip install"
    echo -e "${CYAN}Manually install:${NC} pip3 install hermes-agent python-telegram-bot pyyaml"
fi

# Summary
echo -e "\n${GREEN}${BOLD}╔═══════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}${BOLD}║                                                           ║${NC}"
echo -e "${GREEN}${BOLD}║       ✅  Manual Setup Complete! 🔥                      ║${NC}"
echo -e "${GREEN}${BOLD}║                                                           ║${NC}"
echo -e "${GREEN}${BOLD}╚═══════════════════════════════════════════════════════════╝${NC}\n"

echo -e "${CYAN}Installation Summary:${NC}"
echo -e "  • Install directory: ${BLUE}$INSTALL_DIR${NC}"
echo -e "  • Security skills: ${GREEN}$SKILL_COUNT${NC}"
echo -e "  • Configuration: ${BLUE}$INSTALL_DIR/config/redmess.yaml${NC}"
echo -e "  • Database: ${BLUE}$INSTALL_DIR/umiagent.db${NC}"
echo -e ""

echo -e "${YELLOW}⚠️  REQUIRED: Configure your settings${NC}\n"

echo -e "${CYAN}1. Edit configuration file:${NC}"
echo -e "   ${BLUE}nano $INSTALL_DIR/config/redmess.yaml${NC}"
echo -e ""
echo -e "   ${YELLOW}Change these settings:${NC}"
echo -e "   • ${CYAN}ai.api_key${NC} - Your OpenAI/Anthropic API key"
echo -e "   • ${CYAN}telegram.bot_token${NC} - From @BotFather (if using bot)"
echo -e "   • ${CYAN}godmode.primary_owner${NC} - Your Telegram user ID"
echo -e "   • ${CYAN}telegram.owner_id${NC} - Your Telegram user ID"
echo -e ""

echo -e "${CYAN}2. Inject GODMODE (optional):${NC}"
echo -e "   ${BLUE}$INSTALL_DIR/inject_godmode.sh${NC}"
echo -e ""

echo -e "${CYAN}3. Start Hermes CLI:${NC}"
echo -e "   ${BLUE}$INSTALL_DIR/start_hermes.sh${NC}"
echo -e ""

echo -e "${CYAN}4. Start Telegram Bot:${NC}"
echo -e "   ${BLUE}$INSTALL_DIR/start_bot.sh${NC}"
echo -e ""

echo -e "${RED}⚠️  Legal Reminder:${NC}"
echo -e "  ${YELLOW}Use only on AUTHORIZED systems.${NC}"
echo -e "  ${YELLOW}Unauthorized access is ILLEGAL.${NC}"
echo -e ""

echo -e "${GREEN}Setup complete! Configure your settings and you're ready to go.${NC}\n"
